# Generated by Django 5.1.15 on 2026-07-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('directeur_etudes', 'Directeur des études'), ('eleve', 'Élève'), ('parent', 'Parent / Tuteur')], default='eleve', help_text="Rôle de l'utilisateur dans la plateforme.", max_length=30, verbose_name='Rôle'),
        ),
    ]
