# Generated by Django 5.1.15 on 2026-07-16 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('libelle', models.CharField(help_text="Ex : Minerval 1er terme, Frais d'examen, Frais de labo", max_length=100, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('scolarite', 'Scolarité'), ('examen', 'Examen'), ('laboratoire', 'Laboratoire'), ('activite', 'Activité parascolaire'), ('transport', 'Transport'), ('internat', 'Internat'), ('autre', 'Autre')], default='scolarite', max_length=20, verbose_name='Catégorie')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (USD)')),
                ('est_obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('est_recurrent', models.BooleanField(default=False, help_text="True si le frais s'applique à chaque terme", verbose_name='Récurrent')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_types', to='academic.anneescolaire', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
                'ordering': ['annee_scolaire__date_debut', 'categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='FraisEleve',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('exempt', 'Exempté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_eleves', to='academic.anneescolaire', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='frais', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('frais_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_eleves', to='finance.fraistype', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Frais élève',
                'verbose_name_plural': 'Frais élèves',
                'ordering': ['-annee_scolaire__date_debut', 'eleve__last_name', 'eleve__first_name'],
                'unique_together': {('eleve', 'frais_type', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, default='', help_text='Numéro de transaction Mobile Money, reçu, etc.', max_length=100, verbose_name='Référence')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('frais_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.fraiseleve', verbose_name='Frais')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
