# Generated by Django 5.1.15 on 2026-07-16 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fraiseleve',
            index=models.Index(fields=['statut'], name='finance_fra_statut_399638_idx'),
        ),
        migrations.AddIndex(
            model_name='fraiseleve',
            index=models.Index(fields=['annee_scolaire', 'statut'], name='finance_fra_annee_s_f8d2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='finance_pai_date_pa_45d0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['methode', 'date_paiement'], name='finance_pai_methode_559894_idx'),
        ),
    ]
