# Generated by Django 5.1.15 on 2026-07-15 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('type', models.CharField(choices=[('syllabus', 'Syllabus'), ('support', 'Support de cours'), ('exercice', 'Exercice'), ('tp', 'Travail pratique'), ('examen', 'Examen'), ('livre', 'Livre numérique'), ('corrige', 'Corrigé')], default='syllabus', max_length=20, verbose_name='Type')),
                ('categorie', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercices'), ('evaluation', 'Évaluation'), ('reference', 'Référence'), ('methodologie', 'Méthodologie')], default='cours', max_length=20, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, default=0, help_text='0 pour gratuit', max_digits=8, verbose_name='Prix (USD)')),
                ('fichier', models.FileField(help_text='PDF ou DOCX', upload_to='marketplace/ressources/', verbose_name='Fichier')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='marketplace/couvertures/', verbose_name='Image de couverture')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé'), ('retire', 'Retiré')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('nombre_telechargements', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('auteur', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='ressources_publiees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='academic.classe', verbose_name='Classe')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='academic.cours', verbose_name='Cours')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant payé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('echoue', 'Échec du paiement'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='marketplace.resource', verbose_name='Ressource')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements_log', to='marketplace.resource', verbose_name='Ressource')),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'verbose_name_plural': 'Téléchargements',
                'ordering': ['-created_at'],
            },
        ),
    ]
