# Generated by Django 5.1.15 on 2026-07-15 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant')),
                ('provider', models.CharField(max_length=30, verbose_name='Fournisseur de paiement')),
                ('reference_interne', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Référence interne')),
                ('reference_provider', models.CharField(blank=True, default='', max_length=200, verbose_name='Référence fournisseur')),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('en_cours', 'En cours'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='initie', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.order', verbose_name='Commande')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
