# Generated by Django 5.1.15 on 2026-07-15 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('action', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('correction', 'Correction demandée'), ('valide', 'Validé'), ('rejete', 'Rejeté')], max_length=20, verbose_name='Action')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('action_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_validation', to=settings.AUTH_USER_MODEL, verbose_name='Action effectuée par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validation', to='pedagogy.documentpedagogique', verbose_name='Document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Historique de validation',
                'verbose_name_plural': 'Historiques de validation',
                'ordering': ['-created_at'],
            },
        ),
    ]
