# Generated by Django 5.1.15 on 2026-07-16 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEleve',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('relation', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal'), ('oncle', 'Oncle'), ('tante', 'Tante'), ('grand_parent', 'Grand-parent'), ('frere', 'Frère aîné'), ('soeur', 'Sœur aînée'), ('autre', 'Autre')], default='tuteur', max_length=20, verbose_name='Relation')),
                ('est_contact_principal', models.BooleanField(default=False, help_text='Reçoit les notifications en priorité', verbose_name='Contact principal')),
                ('autorise_consultation', models.BooleanField(default=True, help_text='Notes, bulletins, absences, frais de scolarité', verbose_name='Autorisé à consulter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='parents_charge', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='enfants_charge', to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Liaison parent-élève',
                'verbose_name_plural': 'Liaisons parent-élève',
                'ordering': ['eleve__last_name', 'eleve__first_name', 'relation'],
                'unique_together': {('parent', 'eleve')},
            },
        ),
    ]
