# Generated by Django 5.1.15 on 2026-07-15 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPedagogique',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type', models.CharField(choices=[('fiche_preparation', 'Fiche de préparation'), ('fiche_prevision', 'Fiche de prévision'), ('journal_classe', 'Journal de classe'), ('cahier_composition', 'Cahier de composition'), ('cahier_cotes', 'Cahier des cotes')], max_length=30, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('correction', 'Correction demandée'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('observation_directeur', models.TextField(blank=True, default='', verbose_name='Observation du directeur')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_crees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academic.classe', verbose_name='Classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academic.cours', verbose_name='Cours')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Document pédagogique',
                'verbose_name_plural': 'Documents pédagogiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
