# Generated by Django 5.1.15 on 2026-07-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpedagogique',
            name='fichier',
            field=models.FileField(blank=True, help_text='PDF ou DOCX', null=True, upload_to='documents/pedagogiques/', verbose_name='Fichier'),
        ),
    ]
