# Generated by Django 5.1.15 on 2026-07-16 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['jour', 'heure_debut'], name='schedule_cr_jour_f4dd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['annee_scolaire', 'jour'], name='schedule_cr_annee_s_4076e6_idx'),
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['enseignant', 'jour'], name='schedule_cr_enseign_2a1130_idx'),
        ),
    ]
