# Generated by Django 5.1.15 on 2026-07-16 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date'], name='attendance__date_f93e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['eleve', 'date'], name='attendance__eleve_i_ed458c_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['classe', 'date'], name='attendance__classe__3d3773_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['statut'], name='attendance__statut_fbb32a_idx'),
        ),
    ]
